name: VehicleRemover
main: de.philworld.bukkit.vehicleremover.VehicleRemover
version: $MAVEN-VERSION-NUMBER$
commands:
   removevehicles:
      description: Removes all vehicles in all worlds.
permissions:
    'vehicleremover.*':
        description: Gives access to all VehicleRemover commands.
        default: op
        children:
          vehicleremover.removevehicles: true
    vehicleremover.removevehicles:
      description: Allows the player to remove all vehicles.
      default: op